use_frameworks!

platform :ios, '10.0'

target 'AppMangerKit_Example' do
  pod 'AppMangerKit', :path => '../'

  target 'AppMangerKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
